### ISSUE TITLE
浏览器报错：Antd 的 Modal 组件，API 需要迁移

### ISSUE THREAD

**Issue by shensven** [viewweiwu/amiya#75]
```
Warning: [antd: Modal] `visible` will be removed in next major version, please use `open` instead. 
    at Modal (http://localhost:8000/mf-dep____vendor.14cdd22d.js:136831:62)
    at AyDialog (http://localhost:8000/mf-dep____vendor.14cdd22d.js:112914:21)
    at AyDialogForm (http://localhost:8000/mf-dep____vendor.14cdd22d.js:113100:28)
    at div
    at AySearchTable (http://localhost:8000/mf-dep____vendor.14cdd22d.js:117056:28)
    at Component (http://localhost:8000/components__Device__page.async.js:45:92)
    at div
    at div
    at WaterMark (http://localhost:8000/mf-dep____vendor.14cdd22d.js:77355:24)
    at div
    at div
    at GridContent (http://localhost:8000/mf-dep____vendor.14cdd22d.js:73145:64)
    at div
    at ConfigProviderWrap (http://localhost:8000/mf-dep____vendor.14cdd22d.js:80079:25)
    at PageContainer (http://localhost:8000/mf-dep____vendor.14cdd22d.js:73567:24)
    at Device
    at Suspense
    at RemoteComponent (http://localhost:8000/mf-dep____vendor.14cdd22d.js:104289:25)
    at Outlet (http://localhost:8000/mf-dep____vendor.14cdd22d.js:320541:26)
    at EmptyRoute (http://localhost:8000/src_umi_core_EmptyRoute_tsx.async.js:34:70)
    at Suspense
    at RemoteComponent (http://localhost:8000/mf-dep____vendor.14cdd22d.js:104289:25)
    at Outlet (http://localhost:8000/mf-dep____vendor.14cdd22d.js:320541:26)
    at ApolloProvider (http://localhost:8000/mf-dep____vendor.14cdd22d.js:347937:21)
    at Children (http://localhost:8000/src_umi_umi_ts.async.js:5439:18)
    at Exception (http://localhost:8000/.umi__plugin-layout__Layout.async.js:34:12)
    at main
    at http://localhost:8000/mf-dep____vendor.14cdd22d.js:134209:25
    at http://localhost:8000/mf-dep____vendor.14cdd22d.js:134188:66
    at ErrorBoundary (http://localhost:8000/mf-dep____vendor.14cdd22d.js:88915:90)
    at WrapContent (http://localhost:8000/mf-dep____vendor.14cdd22d.js:71433:82)
    at div
    at section
    at http://localhost:8000/mf-dep____vendor.14cdd22d.js:134225:63
    at http://localhost:8000/mf-dep____vendor.14cdd22d.js:134188:66
    at div
    at Provider (http://localhost:8000/mf-dep____vendor.14cdd22d.js:378264:31)
    at BaseProLayout (http://localhost:8000/mf-dep____vendor.14cdd22d.js:71067:13)
    at ProLayoutProvider (http://localhost:8000/mf-dep____vendor.14cdd22d.js:77552:82)
    at FormProvider (http://localhost:8000/mf-dep____vendor.14cdd22d.js:240031:31)
    at LocaleProvider (http://localhost:8000/mf-dep____vendor.14cdd22d.js:134928:90)
    at ProviderChildren (http://localhost:8000/mf-dep____vendor.14cdd22d.js:127883:24)
    at LocaleReceiver (http://localhost:8000/mf-dep____vendor.14cdd22d.js:134800:90)
    at ConfigProvider (http://localhost:8000/mf-dep____vendor.14cdd22d.js:127998:13)
    at div
    at SWRConfig$1 (http://localhost:8000/mf-dep____vendor.14cdd22d.js:377549:23)
    at ConfigProviderWrap (http://localhost:8000/mf-dep____vendor.14cdd22d.js:80079:25)
    at ProviderChildren (http://localhost:8000/mf-dep____vendor.14cdd22d.js:127883:24)
    at LocaleReceiver (http://localhost:8000/mf-dep____vendor.14cdd22d.js:134800:90)
    at ConfigProvider (http://localhost:8000/mf-dep____vendor.14cdd22d.js:127998:13)
    at ProLayout (http://localhost:8000/mf-dep____vendor.14cdd22d.js:71380:28)
    at http://localhost:8000/.umi__plugin-layout__Layout.async.js:217:66
    at Suspense
    at RemoteComponent (http://localhost:8000/mf-dep____vendor.14cdd22d.js:104289:25)
    at Routes (http://localhost:8000/mf-dep____vendor.14cdd22d.js:103872:76)
    at Router (http://localhost:8000/mf-dep____vendor.14cdd22d.js:320564:15)
    at BrowserRoutes (http://localhost:8000/mf-dep____vendor.14cdd22d.js:103830:23)
    at _LocaleContainer (http://localhost:8000/src_umi_umi_ts.async.js:3442:144)
    at Provider (http://localhost:8000/src_umi_umi_ts.async.js:2272:74)
    at InitialStateProvider (http://localhost:8000/src_umi_umi_ts.async.js:2546:138)
    at Provider (http://localhost:8000/src_umi_umi_ts.async.js:4036:34)
    at ProviderWrapper (http://localhost:8000/src_umi_umi_ts.async.js:4251:135)
    at $8097f9b4a6c197ce$export$bfa587c2c3245948 (http://localhost:8000/mf-dep____vendor.14cdd22d.js:100502:62)
    at Root (http://localhost:8000/src_umi_umi_ts.async.js:5129:24)
    at Browser (http://localhost:8000/mf-dep____vendor.14cdd22d.js:103913:68)
```

**Comment by viewweiwu** [comment]
antd 什么版本

**Comment by viewweiwu** [comment]
会考虑移除

**Comment by shensven** [comment]
`antd@4.23.4`
